schema_version: 1

context:
  version: "2.1.8"

package:
  name: runpodctl
  version: ${{ version }}

source:
  url: https://github.com/runpod/runpodctl/archive/refs/tags/v${{ version }}.tar.gz
  sha256: c4ef64602ac9e057b6df67d5ad0cf168b5e68ed9010a1c0c6b2cf9c31f1a5437

build:
  number: 0
  script:
    - go-licenses save . --save_path=license-files --ignore github.com/runpod/runpodctl
    - if: unix
      then: go build -v -o ${PREFIX}/bin/runpodctl -ldflags="-s -w -X main.Version=${PKG_VERSION}"
    - if: win
      then: go build -v -o %LIBRARY_BIN%\runpodctl.exe -ldflags="-s -X main.Version=%PKG_VERSION%"

requirements:
  build:
    - ${{ compiler("go-nocgo") }}
    - go-licenses

tests:
  - script:
      - runpodctl --version
      - runpodctl --help

about:
  homepage: "https://www.runpod.io"
  repository: https://github.com/runpod/runpodctl
  documentation: https://docs.runpod.io/runpodctl
  license: GPL-3.0-only
  license_file:
    - LICENSE
    - license-files/
  summary: "🧰 | Runpod CLI for pod management"
  description: runpodctl is the cli tool to manage gpu pods, serverless endpoints, and more on [runpod.io](https://runpod.io).

extra:
  recipe-maintainers:
    - eunos-1128
